### ISSUE TITLE
Getting a NoneType on my input

### ISSUE THREAD

**Issue by awqsrem** [pyxv/xvpl-dl#7]
Name changed to Anon for privacy purposes.
Traceback:

"C:\Users\Anon\Downloads\Downloader\~\Downloads\xvideos>python xvpl-dl.py https://www.xvideos.com/favorite/31668773/best

🔞 🍆 💦 XVIDEOS PLAYLIST DOWNLOADER (xvpl-dl)

🛠️  settings:

  custom_dl_dir:
  dedupe_all: True

📚 playlists queued:

   ➡️ https://www.xvideos.com/favorite/31668773/best

📥 commencing download...

⏳ initialising playlist...
   ➡️ https://www.xvideos.com/favorite/31668773/best
Traceback (most recent call last):
  File "C:\Users\Anon\Downloads\Downloader\~\Downloads\xvideos\xvpl-dl.py", line 128, in <module>
    playlist = Playlist(pl)
  File "C:\Users\Anon\Downloads\Downloader\~\Downloads\xvideos\xvpl-dl.py", line 47, in __init__
    page = Page(page_url)
  File "C:\Users\Anon\Downloads\Downloader\~\Downloads\xvideos\xvpl-dl.py", line 110, in __init__
    self.extract_video_urls()
  File "C:\Users\Anon\Downloads\Downloader\~\Downloads\xvideos\xvpl-dl.py", line 114, in extract_video_urls
    video_elements = videos_block.find_all(attrs={self.id_attrib: True})
AttributeError: 'NoneType' object has no attribute 'find_all'

**Comment by kdu9r** [comment]
I'm very newbie with coding, I'd like to know if you found the solution for this error, I'm trying to download a playlist w/ a lot of videos. Please, help us

**Comment by jwvanderbeck** [comment]
I think I've managed to get it working but I need to do a bit more testing to be sure.  I'll post a PR once I am though I don't know if this repo is active or not
